name: My Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00 UTC everyday
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update Readme by Bruno Faria
    runs-on: ubuntu-latest
    steps:
      - uses: brunofaria1322/brunofaria1322@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}