name: My Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00 Europe/Lisbon everyday
    - cron: '0 23 * * *'

jobs:
  update-readme:
    name: Update Readme by Bruno Faria
    runs-on: ubuntu-latest
    steps:
      - uses: brunofaria1322/brunofaria1322@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}